name: Check required secrets

on:
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print presence of required secrets
        run: |
          echo "OPENAI_API_KEY: ${OPENAI_API_KEY:+present}${OPENAI_API_KEY:+'present'}${OPENAI_API_KEY:-absent}"
          echo "FIREBASE_SERVICE_KEY: ${FIREBASE_SERVICE_KEY:+present}${FIREBASE_SERVICE_KEY:+'present'}${FIREBASE_SERVICE_KEY:-absent}"
          echo "GCP_PROJECT: ${GCP_PROJECT:+present}${GCP_PROJECT:+'present'}${GCP_PROJECT:-absent}"
          echo "GCP_SA_KEY: ${GCP_SA_KEY:+present}${GCP_SA_KEY:+'present'}${GCP_SA_KEY:-absent}"
          echo "VITE_API_BASE: ${VITE_API_BASE:+present}${VITE_API_BASE:+'present'}${VITE_API_BASE:-absent}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIREBASE_SERVICE_KEY: ${{ secrets.FIREBASE_SERVICE_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
