name: PR checks

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Backend - install deps
        run: npm ci --prefix backend

      - name: Backend - run tests
        run: npm test --prefix backend

      - name: Backend - syntax check
        run: node --check backend/index.js || true

      - name: Frontend - install deps
        run: npm ci --prefix frontend

      - name: Frontend - strict verify build
        env:
          # Provide a known VITE_API_BASE for PR checks. This will be enforced
          # by the pre-build script and verified in the generated sourcemap.
          VITE_API_BASE: "http://localhost:8080"
        run: |
          echo "Running verify build with VITE_API_BASE=$VITE_API_BASE"
          npm run build:verify --prefix frontend
          echo "Searching built artifacts (including sourcemaps) for VITE_API_BASE"
          if [ -f frontend/dist/VITE_API_BASE.txt ]; then
            FOUND=$(cat frontend/dist/VITE_API_BASE.txt)
            if [ "$FOUND" = "$VITE_API_BASE" ]; then
              echo "✅ VITE_API_BASE verified in frontend/dist/VITE_API_BASE.txt"
            else
              echo "❌ frontend/dist/VITE_API_BASE.txt contains '$FOUND' but expected '$VITE_API_BASE' — failing PR check"
              exit 1
            fi
          else
            echo "❌ frontend/dist/VITE_API_BASE.txt not found — failing PR check"
            exit 1
          fi

      - name: Repo quick scan (secrets)
        run: |
          # quick check to ensure no accidental secret files are present in PR
          git ls-files --others --exclude-standard | grep -E '(^|/)\.env|serviceAccountKey.json' || true
