name: Staging smoke tests

on:
  workflow_dispatch:
    inputs:
      backend_url:
        description: 'Optional: Backend base URL to test (overrides secret STAGING_BACKEND_URL)'
        required: false

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Determine backend URL
        id: backend
        run: |
          if [ -n "${{ github.event.inputs.backend_url }}" ]; then
            echo "Using input backend_url"
            echo "url=${{ github.event.inputs.backend_url }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ secrets.STAGING_BACKEND_URL }}" ]; then
            echo "Using secret STAGING_BACKEND_URL"
            echo "url=${{ secrets.STAGING_BACKEND_URL }}" >> $GITHUB_OUTPUT
          else
            echo "No backend URL provided. Set workflow input 'backend_url' or secret STAGING_BACKEND_URL." >&2
            exit 1
          fi

      - name: Run smoke tests
        env:
          BACKEND_URL: ${{ steps.backend.outputs.url }}
        run: |
          echo "Testing backend: $BACKEND_URL"
          set -euo pipefail
          # health endpoint
          curl -sSf "$BACKEND_URL/health" || (echo "Health endpoint failed" && exit 1)
          echo "✅ Health OK"
          # topics categories
          curl -sSf -X POST "$BACKEND_URL/api/topics/categories" -H 'Content-Type: application/json' -d '{}' || (echo "Topics categories failed" && exit 1)
          echo "✅ Topics categories OK"
          # dialog (generate minimal request)
          curl -sSf -X POST "$BACKEND_URL/api/dialog" -H 'Content-Type: application/json' -d '{"area":"Medicine","topic":"fever","language":"en","model":"gpt-4o-mini"}' || (echo "Dialog endpoint failed" && exit 1)
          echo "✅ Dialog OK"
